# Site
name: "Free Thoughts"
title: "Free Thoughts"
description: "Write your ideas, thoughts, reviews, research and analysis about anything and everything."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
google_analytics: 'G-H2FG74WDBC'
disqus: 'free-thoughts-1'
# mailchimp-list: "https://xyz.us7.list-manage.com/subscribe/post?u=1659f823b7c9374c657209e51&amp;id=711292be44" 
include: ["_pages"]
permalink: /:title/
# url: "https://blog.riwajchalise.com.np/"

# Authors
collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
    # Subham:
    #   name: Subham Pokharel
    #   display_name: Subham
    #   avatar:  
    #   email: natureboysubham@gmail.com
    #   twitter: https://twitter.com/wowthemesnet
    #   description: "Author of Mediumish, a Bootstrap Medium styled template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
    
    # john:
    #   name: Riwaj Chalise
    #   display_name: Riwaj    
    #   avatar: 'assets/images/riwaj.jpg'
    #   email: wazzree@gmail.com
    #   web: https://www.riwajchalise.com.np
    #   twitter: https://twitter.com/riwaj_
    #   description: ""

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
